version: '3.6'
services:
  # app:
  #   build:
  #     context: ./app
  #   depends_on:
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis
  #   ports:
  #     - "5000:5000"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: